hallvids/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(),name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('change_password', views.change_password, name='change_password'),
    # hall favorite video thread
    path('favoritevideos/create', views.CreateFav.as_view(), name='create_fav'),
    path('favoritevideos/<int:pk>', views.DetailFav.as_view(), name='detail_fav'),
    path('favoritevideos/<int:pk>/update', views.UpdateFav.as_view(), name='update_fav'),
    path('favoritevideos/<int:pk>/delete', views.DeleteFav.as_view(), name='delete_fav'),
    # Video
    path('favoritevideos/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

halls/forms.py
from .models import Video,Hall
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username',)
        exclude = ('password',)

# model based form
class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ['url']
        labels = {'url':'YouTube URL'}

class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos')

halls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, update_session_auth_hash
from .models import Hall, Video
from .forms import VideoForm, SearchForm, EditProfileForm
from django.forms import formset_factory
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import urllib
import requests


YOUTUBE_API_KEY = 'AIzaSyC5efsoEqcwz0TQf3M2JsfLeP1jYlI-pTI'


# Create your views here.
def home(request):
    recent_fav = Hall.objects.all().order_by('-id')[:3]
    popular_fav = [Hall.objects.get(pk=1),Hall.objects.get(pk=2)]
    return render(request, 'halls/home.html', {'recent_fav':recent_fav, 'popular_fav':popular_fav})

@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', {'halls':halls})

@login_required
def add_video(request, pk):
    VideoFormSet = formset_factory(VideoForm, extra=3)

    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    # if someone tries to add somdthing and they are not the correct owner
    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        # form validation making the video objects
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.hall = hall
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YOUTUBE_API_KEY }')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_fav', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('The url you entered MUST be from youtube.com')

            # template below
    return render(request, 'halls/add_video.html', {'form':form, 'search_form':search_form, 'hall':hall})

@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    else:
        return JsonResponse({'error':'unable to validate form'})

class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name='halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        else:
            return video

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect ('home')
    else:
            form = EditProfileForm(instance=request.user)

    context={'form':form}
    return render(request, 'registration/edit_profile.html', context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect ('home')
    else:
            form = PasswordChangeForm(user=request.user)

    context={'form':form}
    return render(request, 'registration/change_password.html', context)


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'
###################################################
# this function customizes the class and logs
# the user in automatically after they sign up
###################################################
    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view

class CreateFav(LoginRequiredMixin, generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'halls/create_fav.html'
    success_url = reverse_lazy('dashboard')
###################################################
# the funciton below connects/saves a user to the title
# hall that the user created, in the admin database
###################################################
    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateFav, self).form_valid(form)
        return redirect('dashboard')

class DetailFav(generic.DetailView):
    model = Hall
    template_name='halls/detail_fav.html'

class UpdateFav(LoginRequiredMixin, generic.UpdateView):
    model = Hall
    template_name='halls/update_fav.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateFav, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        else:
            return hall

class DeleteFav(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name='halls/delete_fav.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteFav, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        else:
            return hall

halls/templates/halls/add_video.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <h2>Add a Video to your {{ hall.title }} Collection!</h2>
  <form id="submit_video" method="post">
    {% csrf_token %}
    {% load widget_tweaks %}
      {% for field in form %}
        <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
          {{ field.errors }}
          {{ field.label_tag }}
          {% render_field field class="form-control" %}
        </div>
      {% endfor %}


      <button type="submit" class="btn btn-primary">Add Now!</button>
  </form>
  <br>

<h3>OR</h3>

<form>
  {% for field in search_form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
    </div>
  {% endfor %}
</form>
  <div id="search_results"></div>
    <script>
      var delayedTimer;
      $('#id_search_term').keyup(function(){
        clearTimeout(delayedTimer);
        $('#search_results').text('Searching YouTube.....');
        delayedTimer = setTimeout(function(){
          var text = $('#id_search_term').val();
          $.ajax({
            url: '/video/search',
            data: {
              'search_term': text
            },
            dataType: 'json',
            success: function(data) {
              var results = '';
              $('#search_results').text('');
              results += '<div class="row">';
              data['items'].forEach(function(video) {
                results += '<div class ="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                results += '<iframe width="100%" height="250" src="https://www.youtube.com/embed/' +video['id']['videoId']+
                  '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
                results += '<a href="#" class="btn btn-primary" onclick="addVideo(\''+ video['id']['videoId'] +'\')">Add Video</a></div></div></div>';
              });
              results += '</div>';
              $('#search_results').append(results);
            }
          });
        }, 1500);
      });
      function addVideo(video_id){
        $('#id_url').val('https://www.youtube.com/watch?v='+video_id);
        $('#submit_video').submit();
      }
    </script>




</div>





{% endblock %}

halls/templates/halls/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Favorite YouTube Collections</title>
    <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- custom css -->
  <link  rel="stylesheet" href="{% static 'custom.css' %}">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Hind+Siliguri" rel="stylesheet">
        <!-- star -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    .start:hover{
      color:rgb(255, 251, 53);
      transform: scale(1.08);
      transition: 0.5s ease;
    }
    .monkey:hover{
      transform: scale(1.08);
      transition: 0.3s ease;
    }
    .banner{
      border-radius: 45px;
      position: relative;
      margin: 5% auto;
      top: 20px;
      height: 320px;
      width: 620px;
      background: rgb(255, 72, 48,0.63);
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.5);
    }
    @media only screen and (max-width: 620px) {
      /* For mobile phones: */
      [class*="banner-"]{
      width: 100%;
      }
    }
      @keyframes bounce {
  	0%, 20%, 60%, 100% {
  		-webkit-transform: translateY(0);
  		transform: translateY(0);
  	}

  	40% {
  		-webkit-transform: translateY(-20px);
  		transform: translateY(-20px);
  	}

  	80% {
  		-webkit-transform: translateY(-10px);
  		transform: translateY(-10px);
  	}
  }
    .colltitle:hover {
  	animation: bounce 1s;
  }
  </style>
</head>

<body style="background-image: url('http://sfwallpaper.com/images/abstract-light-color-wallpaper-17.jpg'); background-repeat: no-repeat; background-attachment:fixed;font-family: 'Hind Siliguri', sans-serif;">


<div class="fixed-top d-flex flex-column flex-md-row align-items-center p-3 px-md-4" style="background-color: rgb(255, 246, 214,0.85);">
  <h4 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Favorite Video Collections</a></h4>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    <a class="p-2 text-dark" href="{% url 'dashboard' %}"><span id="star" class="fa"></span> My Dashboard</a>
      <script>
          function ratestar() {
          var a;
          a = document.getElementById("star");
          a.innerHTML = "&#xf006;";
          setTimeout(function () {
              a.innerHTML = "&#xf123;";
            }, 1000);
          setTimeout(function () {
              a.innerHTML = "&#xf005;";
            }, 2000);
          }
          ratestar();
          setInterval(ratestar, 3000);
      </script>
    <a class="p-2 text-dark" href="{% url 'edit_profile' %}"><span class="fa fa-pencil-square-o"></span> Edit Profile</a>
    <a class="p-2 text-dark" href="{% url 'logout' %}"><span class="fa fa-user-circle-o"></span> Log Out</a>
    {% else %}
    <a class="p-2 text-dark" href="{% url 'login' %}"><span class="fa fa-user-circle-o"></span> Login</a>
    {% endif %}
  </nav>
  {% if user.is_authenticated == False %}
  <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
  {% endif %}
</div>
<br>



  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  {% block content %}
  {% endblock %}

</body>

</html>

halls/templates/halls/create_fav.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <h2>Create a Video Thread</h2>
  <form method="post">
    {% csrf_token %}
    {% load widget_tweaks %}
    {% for field in form %}
      <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
        {{ field.errors }}
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
      </div>
    {% endfor %}
      <input type="submit" value="Create" class="btn btn-primary">
  </form>
</div>





{% endblock %}

halls/templates/halls/dashboard.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <div class="text-center">
      <h2>@{{ user.username }}'s Favorite Video Collections</h2>
      <a href="{% url 'create_fav' %}" class="btn btn-success" role="button">New Collection</a>

  </div>
  <br>

    {% for hall in halls %}

    <h2 class="colltitle"><a id="halltitle" style="text-decoration :none;color: rgb(255, 72, 48);" href="{% url 'detail_fav' hall.id %}">{{ hall.title }}</a></h2>
    <a href="{% url 'add_video' hall.id %}" class="btn btn-primary"><span class="fa fa-plus"></span> Add Video</a>
    <a href="{% url 'update_fav' hall.id %}" class="btn btn-warning"><span class="fa fa-pencil"></span> Edit Collection</a>

      <div class="row">
      {% for video in hall.video_set.all %}
        <div class ="col-md-4 mt-3">
          <div class="monkey">
          <div class="card mb-4 shadow-lg">
            <iframe width="100%" height="250" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              <div class="card-body"><p class="card-text">{{ video.title }}</p>
            </div>
          </div>
        </div>
        </div>
      {% endfor %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

halls/templates/halls/delete_fav.html
{% extends 'halls/base.html' %}
{% block content %}
<div class="container">
  <h2>Delete this Collection?</h2>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <h3><a href="{% url 'detail_fav' hall.id %}">{{ hall.title }}</a></h3>
      <br>
      <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </form>
</div>

{% endblock %}

halls/templates/halls/delete_video.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <h2>Delete Video</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button type="submit" class="btn btn-danger">Confirm Delete</button>
  </form>



<div class="row">
  <div class ="col-md-4 mt-3">
    <div class="card mb-4 shadow-sm">
    <iframe width="100%" height="250" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="card-body">
      <p class="card-text">{{ video.title }}</p>
      </div>
    </div>
  </div>
</div>




</div>

{% endblock %}

halls/templates/halls/detail_fav.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <h2 style="color:rgb(255, 72, 48);" id="halltitle">{{ hall.title }}</h2>
  <h5 class="text-muted">@{{ hall.user.username }}</h5>

  {% if user.id == hall.user.id %}
  <a href="{% url 'add_video' hall.id %}" class="btn btn-primary"><span class="fa fa-plus"></span> Add Video</a>
  <a href="{% url 'update_fav' hall.id %}" class="btn btn-warning"><span class="fa fa-pencil"></span> Edit Collection</a>
  {% endif %}

    <div class="row">
    {% for video in hall.video_set.all %}
      <div class ="col-md-4 mt-3">
        <div class="monkey">
          <div class="card mb-4 shadow-sm">
              <iframe width="100%" height="250" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>
            </div>
          </div>
        </div>
        <a href="{% url 'delete_video' video.id %}" class="btn btn-danger"><span class="fa fa-scissors"></span> Delete Video</a>

      </div>

    {% endfor %}
    </div>
</div>
{% endblock %}

halls/templates/halls/home.html
{% extends 'halls/base.html' %}
{% block content %}

<div class="banner">
    <div class="container">
      <center>
        <br>
        <h1 class="banner-">What are your Favorite <br> Video Collections?</h1>
        <h3 class="banner-">Make your own Favorite Video Collections!</h3>
        <h3 class="banner-">Share your Videos with the World!</h3>
        <h3 class="banner-">View other people's Favorite Collections!</h3>
        <a style="text-decoration :none;" href="{% url 'create_fav' %}"><h2 class="start">Start Your Video Collection!</h2></a>
    </center>
  </div>
</div>

<div class="container">
  <h1 class="text-center">Popular Collections</h1>
  {% for hall in popular_fav %}
  <h2 class="colltitle"><a style="text-decoration : none; color: red;" href="{% url 'detail_fav' hall.id %}">{{ hall.title }}</a></h2>

    <div class="row">
    {% for video in hall.video_set.all %}
      <div class ="col-md-4 mt-3">
        <div class="monkey">
        <div class="card mb-4 shadow-lg">
          <iframe width="100%" height="250" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  {% endfor %}




  <h1 class="text-center">Recent Uploads</h1>
  {% for hall in recent_fav %}
  <h2><a style="text-decoration : none; color: red;" href="{% url 'detail_fav' hall.id %}">{{ hall.title }}</a></h2>

    <div class="row">
    {% for video in hall.video_set.all %}
      <div class ="col-md-4 mt-3">
        <div class="monkey">
        <div class="card mb-4 shadow-lg">
        <iframe width="100%" height="250" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body"><p class="card-text">{{ video.title }}</p>
          </div>
        </div>
      </div>
      </div>
    {% endfor %}
    </div>
  {% endfor %}




  </div>
</div>
{% endblock %}

halls/templates/halls/update_fav.html
{% extends 'halls/base.html' %}
{% block content %}
<br>
<br>
<div class="container">
  <h2>Edit Collection</h2>
  <form method="post">
    {% csrf_token %}
    {% load widget_tweaks %}
    {% for field in form %}
      <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
        {{ field.errors }}
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
      </div>
    {% endfor %}
    <input type="submit" value="Save" class="btn btn-success">
    <a class="btn btn-danger" href="{% url 'delete_fav' hall.id %}"><span class="fa fa-scissors"></span> Delete Thread</a>

  </form>
  <br>
</div>






{% endblock %}